module.exports.message = {
    "success": "success",
    "msg1": "User already exists",
    "msg2": "You have registered, need to verify your account",
    "msg3": "Wrong OTP",
    "msg4": "Your account has been verified",
    "msg5": "User is not exist",
    "msg6": "Wrong password",
    "msg7": "Logged-in successfully",
    "msg8": "OTP sent",
    "msg9": "No code received",
    "msg10": "Password has been changed",
    "msg11": "You are changing your password after 10 minutes",
    "msg12": "Previous password is wrong",
    "msg13": "Your info has been updated",
    "msg14": "You can not get others information",
    "msg15": "Code is empty",
    "msg16": "Email is required",
    "msg17": "uploadded successfully",
    "msg18": "You can not update others information",
    "msg19": "User updated successfully",
    "msg20": "You can not delete others information",
    "msg21": "User deleted successfully",
    "msg22": "Admin can not be deleted",
    "msg23": "Category already exists",
    "msg24": "Category has been created",
    "msg25": "Token not found",
    "msg26": "Token is not valid",
    "msg27": "Only admin can do",
    "msg28": "Category not found",
    "msg29": "Category deleted successfully",
    "msg30": "Expense created successfully",
    "msg31": "Expense not found",
    "msg32": "You can not update other's expenses",
    "msg33": "You can not delete other's expenses",
    "msg34": "Expense deleted successfully",
    "msg35": "All category fetched successfully",
    "msg36": "All expenses fetched successfully",
    "msg37": "Last three months expenses fetched successfully",
    "msg38": "You can not get other's expenses",
    "msg39": "Expense data fetched successfully",
    "msg40": " Either date or category is required",
    "msg41": "This category's budget is exist",
    "msg42": "Budget has been set successfully",
    "msg43": "Budget is not exist",
    "msg44": "You can not update other's budget",
    "msg45": "Update budget successfully",
    "msg46": "You can not delete other's budget",
    "msg47": "Delete budget successfully",
    "msg48": "All budget fetched successfully",
    "msg49": "Please update your phone number before using this service",
    "msg50": "Created successfully",
    "msg51": "No data found",
    "msg52": "You can not update others's borrow or lent",
    "msg53": "Updated successfully",
    "msg54": "Fetched successfully",
    "msg55": "Deleted successfully",
    "msg56": "keys should be numbers",
}


module.exports.MAILCODE = {
    REGISTRATION: "registration",
    RESET_PASSWORD: "resetpassword",
    CATEGORY: "category",
};


module.exports.ROLES = {
    ADMIN: "admin",
    USER: "user",
};



